api:
  dashboard: true

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure

  postgresdb:
    address: :5432

  websecure:
    address: :443
    http:
      middlewares:
        - secureHeaders@file
      tls:
        certResolver: letsencrypt
        domains:
          - main: '<ADD_YOUR_TOPLEVEL_DOMAIN>'
            sans:
              - '*.<ADD_YOUR_TOPLEVEL_DOMAIN>'

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    filename: conf.yml

certificatesResolvers:
  letsencrypt:
    acme:
      email: <ADD_YOUR_MAIL>
      storage: acme.json
      dnsChallenge:
        provider: "digitalocean"
        delayBeforeCheck: 120